version: "3"

services:
  app:
    container_name: app-sportx
    restart: always
    image: app-sportx
    ports:
      - "3333:3333"
    links:
      - sqlserver  
    build: .
  sqlserver:
    container_name: sqlserver
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@55w0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - .:/usr/src/app/db